/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package za.ac.cput.project3;

/**
 *
 * @author methysmacbookpro32
 */
public class Prompt2 extends javax.swing.JFrame {

    /**
     * Creates new form Prompt2
     */
    public Prompt2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Afternoon = new javax.swing.JCheckBox();
        Morning = new javax.swing.JCheckBox();
        Evening = new javax.swing.JCheckBox();
        availableanytime = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        couse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        avai = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102,102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 230, 89));
        jLabel1.setText("When are you available for lessons?");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        Afternoon.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Afternoon.setForeground(new java.awt.Color(255, 230, 89));
        Afternoon.setText("Afternoon");
        Afternoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfternoonActionPerformed(evt);
            }
        });

        Morning.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Morning.setForeground(new java.awt.Color(255, 230, 89));
        Morning.setText("Morning ");
        Morning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorningActionPerformed(evt);
            }
        });

        Evening.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Evening.setForeground(new java.awt.Color(255, 230, 89));
        Evening.setText("Evening");
        Evening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EveningActionPerformed(evt);
            }
        });

        availableanytime.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        availableanytime.setForeground(new java.awt.Color(255, 230, 89));
        availableanytime.setText("I am available anytime - l am flexible");
        availableanytime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableanytimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(availableanytime, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Morning)
                        .addGap(44, 44, 44)
                        .addComponent(Afternoon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Evening)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Afternoon)
                    .addComponent(Morning)
                    .addComponent(Evening))
                .addGap(51, 51, 51)
                .addComponent(availableanytime)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/NetBeansProjects/Project3/image resorces/contact us icons/icons8-back-arrow-50.png")); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/NetBeansProjects/Project3/image resorces/contact us icons/icons8-forward-button-50.png")); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, 30));

        couse.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/NetBeansProjects/Project3/image resorces/sergey-zolkin-_UeY8aTI6d0-unsplash.jpeg")); // NOI18N
        couse.setText("jLabel2");
        getContentPane().add(couse, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 330, 400));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/NetBeansProjects/Project3/image resorces/-background-study-99060294.jpg")); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 17, 100, 20));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        num1.setText("jLabel2");
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 60, -1));

        avai.setText("jLabel6");
        getContentPane().add(avai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 60, -1));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu2.setForeground(new java.awt.Color(102, 102, 102));
        jMenu2.setText("Find A tutor");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/Desktop/tutorial_System/src/image resorces/icons8-ibooks-48.png")); // NOI18N
        jMenuItem1.setText("Search for Tutor");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(102, 102, 102));
        jMenu3.setText("Resources");

        jMenuItem2.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/Desktop/tutorial_System/src/image resorces/book images/icons8-stack-of-paper-24.png")); // NOI18N
        jMenuItem2.setText("Free eBooks");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/Desktop/tutorial_System/src/image resorces/book images/icons8-storytelling-24.png")); // NOI18N
        jMenuItem3.setText("Search For eBooks");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon("/Users/methysmacbookpro32/Desktop/tutorial_System/src/image resorces/book images/icons8-storytelling-24.png")); // NOI18N
        jMenuItem4.setText("Search for Past Exam papers");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MorningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorningActionPerformed
       dispose();
       Tutor as= new Tutor();  
       as.couse.setText(couse.getText());//COURSE 
       as.numbre.setText(num1.getText());//STUDENT NUMBER avai
       as.studentAva.setText(avai.getText());//STUDENT NUMBER avai
       as.time.setText(Morning.getText()); //time
       as.SELECTPICTURES();
       as.show();

    }//GEN-LAST:event_MorningActionPerformed

    private void AfternoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfternoonActionPerformed
       dispose();
        Tutor as= new Tutor();  
       as.couse.setText(couse.getText());//COURSE 
       as.numbre.setText(num1.getText());//STUDENT NUMBER 
       as.studentAva.setText(avai.getText());//STUDENT  avai online or onather
       as.time.setText(Afternoon.getText()); //time  
       as.SELECTPICTURES();
       as.show();
    }//GEN-LAST:event_AfternoonActionPerformed

    private void EveningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EveningActionPerformed
        dispose();
        Tutor as= new Tutor();  
       as.couse.setText(couse.getText());//COURSE 
       as.numbre.setText(num1.getText());//STUDENT NUMBER 
       as.studentAva.setText(avai.getText());//STUDENT  avai online or onather
       as.time.setText(Evening.getText()); //time 
       as.show();
    }//GEN-LAST:event_EveningActionPerformed

    private void availableanytimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableanytimeActionPerformed
       dispose();
       Tutor as= new Tutor();  
       as.couse.setText(couse.getText());//COURSE 
       as.numbre.setText(num1.getText());//STUDENT NUMBER 
       as.studentAva.setText(avai.getText());//STUDENT  avai online or onather
       as.time.setText(availableanytime.getText()); //time 
       as.SELECTPICTURES();
       as.show();
    }//GEN-LAST:event_availableanytimeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Afternoon;
    private javax.swing.JCheckBox Evening;
    private javax.swing.JCheckBox Morning;
    public javax.swing.JLabel avai;
    private javax.swing.JRadioButton availableanytime;
    public javax.swing.JLabel couse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel num1;
    // End of variables declaration//GEN-END:variables
}
