/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package za.ac.cput.project3;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author methysmacbookpro32
 */
public class Tutor extends javax.swing.JFrame {

    /**
     * Creates new form Tutor
     */
    public Tutor() {
        initComponents();
        jButton3.setEnabled(false);
        apply.setEnabled(false);
        jButton5.setEnabled(false);
        SELECTPICTURES();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Sunday = new javax.swing.JCheckBox();
        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        jSlider1 = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TIMESTUDENT = new javax.swing.JLabel();
        timesss = new javax.swing.JLabel();
        getimage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lectunamessss1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        money1 = new javax.swing.JLabel();
        availecture1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lecturess2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        money2 = new javax.swing.JLabel();
        availecture2 = new javax.swing.JCheckBox();
        apply = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        money3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        availecture3 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentAva = new javax.swing.JLabel();
        couse = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        numbre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Elementary", "Primary", "High School", "Tertiary School", "Adult" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 203, 39));

        jLabel1.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Availability");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 203, 28));

        Sunday.setForeground(new java.awt.Color(255, 255, 255));
        Sunday.setText("Sunday");
        jPanel1.add(Sunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 216, 82, -1));

        Monday.setForeground(new java.awt.Color(255, 255, 255));
        Monday.setText("Monday");
        jPanel1.add(Monday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 243, 82, -1));

        Tuesday.setForeground(new java.awt.Color(255, 255, 255));
        Tuesday.setText("Tuesday");
        jPanel1.add(Tuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 270, 82, -1));

        Wednesday.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday.setText("Wednesday");
        jPanel1.add(Wednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 297, -1, -1));

        Saturday.setForeground(new java.awt.Color(255, 255, 255));
        Saturday.setText("Saturday");
        jPanel1.add(Saturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 351, 82, -1));

        Thursday.setForeground(new java.awt.Color(255, 255, 255));
        Thursday.setText("Thursday");
        jPanel1.add(Thursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 324, 82, -1));
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 433, -1, -1));

        jLabel17.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Tutor Age: 18 and up");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 410, 203, -1));

        jLabel18.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Student Level");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 203, -1));
        jPanel1.add(TIMESTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 582, -1, -1));
        jPanel1.add(timesss, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 459, -1, -1));
        jPanel1.add(getimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 190, 170));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("I am very experienced Java tutor, father of 4");

        lectunamessss1.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        lectunamessss1.setForeground(new java.awt.Color(255, 255, 255));
        lectunamessss1.setText("Serge Kimpoki");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("I have helped many students improve their test scores and course ");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("grades by multiple letters ");

        money1.setForeground(new java.awt.Color(255, 204, 0));
        money1.setText("$80/hour");

        availecture1.setForeground(new java.awt.Color(0, 211, 179));
        availecture1.setText("Availability");
        availecture1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availecture1ActionPerformed(evt);
            }
        });

        jButton3.setText("Apply");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jCheckBox7))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lectunamessss1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(money1))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(availecture1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lectunamessss1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(money1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availecture1)
                            .addComponent(jButton3))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jCheckBox7)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturess2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lecturess2.setForeground(new java.awt.Color(255, 255, 255));
        lecturess2.setText("Kululo Sholoko");
        jPanel3.add(lecturess2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 8, 147, 20));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 8, 178, 152));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Specializing in Math and Computer Science");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 46, 381, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("I have a bachelors degree in computer science and I worked for a ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 72, -1, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("software company for three years.Java is one of the primary ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 98, 387, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("languages I the primary languages I ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 124, 352, 20));

        money2.setForeground(new java.awt.Color(255, 204, 0));
        money2.setText("$ 120/hour");
        jPanel3.add(money2, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 8, -1, 20));

        availecture2.setForeground(new java.awt.Color(0, 211, 179));
        availecture2.setText("Availability");
        availecture2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availecture2ActionPerformed(evt);
            }
        });
        jPanel3.add(availecture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 151, -1, -1));

        apply.setText("Apply");
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });
        jPanel3.add(apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 150, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prince Mutamba");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("A data scientist with masters in Engineering");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("I graduated from biomedical engineering and earned a master's ");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("in electrical engineering with a 3.91 GPA. I earned more ");

        money3.setForeground(new java.awt.Color(255, 204, 0));
        money3.setText("$110/hour");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(" more than 15 certifications in data science from Duke, ");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Johns Hopkins, and San Diego University");

        availecture3.setForeground(new java.awt.Color(0, 211, 179));
        availecture3.setText("Availability");
        availecture3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availecture3ActionPerformed(evt);
            }
        });

        jButton5.setText("Apply");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(money3))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(availecture3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(money3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availecture3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        jButton1.setText("In-person");

        jButton2.setText("Online");

        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(numbre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(couse, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentAva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(numbre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(couse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentAva, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void availecture1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availecture1ActionPerformed
        
        if(availecture1.isSelected()){
        Sunday.setSelected(true);
        Tuesday.setSelected(true);
        Thursday.setSelected(true);
        availecture2.setEnabled(true);
        availecture3.setEnabled(true);
        
        jButton3.setEnabled(true);
        availecture2.setEnabled(false);
        availecture3.setEnabled(false);
        }else{
        Sunday.setSelected(false);
        Tuesday.setSelected(false);
        Thursday.setSelected(false);
        availecture2.setEnabled(true);
        availecture3.setEnabled(true);
        jButton3.setEnabled(false);
        
      
        }
        
    }//GEN-LAST:event_availecture1ActionPerformed

    private void availecture2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availecture2ActionPerformed
     
        
        if(availecture2.isSelected()){
        Wednesday.setSelected(true);
        Tuesday.setSelected(true);
        Saturday.setSelected(true);
        availecture1.setEnabled(false);
        availecture3.setEnabled(false);
         ;
        apply.setEnabled(true);
        
        availecture1.setEnabled(false);
        availecture3.setEnabled(false);
        }else{
        Wednesday.setSelected(false);
        Tuesday.setSelected(false);
        Saturday.setSelected(false);
        availecture1.setEnabled(true);
        availecture3.setEnabled(true);
        apply.setEnabled(false);
        
        }
        
    }//GEN-LAST:event_availecture2ActionPerformed

    private void availecture3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availecture3ActionPerformed
         
        if(availecture3.isSelected()){
        Wednesday.setSelected(true);
        Tuesday.setSelected(true);
        Saturday.setSelected(true);
        availecture1.setEnabled(false);
        availecture2.setEnabled(false);
         jButton5.setEnabled(true);
        
        availecture1.setEnabled(false);
        availecture2.setEnabled(false);
        }else{
        Wednesday.setSelected(false);
        Tuesday.setSelected(false);
        Saturday.setSelected(false);
        availecture1.setEnabled(true);
        availecture2.setEnabled(true);
        jButton5.setEnabled(false);
       
        }
    }//GEN-LAST:event_availecture3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        Payment pay= new Payment();
        pay.StudentNumber.setText(numbre.getText()); //student number
        pay.courseP.setText(couse.getText()); //student couse
        pay.avaible.setText(studentAva.getText()); //student AVA Online or in person
        pay.times.setText(time.getText()); //student number time Evening or Morning
        pay.lecturename.setText(lectunamessss1.getText()); //student number
        pay.payamout.setText(money1.getText()); //student number money of lecture by hour
        pay.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        dispose();
        Payment pay= new Payment();
        pay.StudentNumber.setText(numbre.getText()); //student number
        pay.courseP.setText(couse.getText()); //student couse
        pay.avaible.setText(studentAva.getText()); //student AVA Online or in person
        pay.times.setText(time.getText()); //student number time Evening or Morning
        pay.lecturename.setText(lecturess2.getText()); //student number
        pay.payamout.setText(money2.getText()); //student number money of lecture by hour
        pay.show();
    }//GEN-LAST:event_applyActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         dispose();
        Payment pay= new Payment();
        pay.StudentNumber.setText(numbre.getText()); //student number
        pay.courseP.setText(couse.getText()); //student couse
        pay.avaible.setText(studentAva.getText()); //student AVA Online or in person
        pay.times.setText(time.getText()); //student number time Evening or Morning
        pay.lecturename.setText(jLabel3.getText()); //student number
        pay.payamout.setText(money3.getText()); //student number money of lecture by hour
        pay.show();
    }//GEN-LAST:event_jButton5ActionPerformed
public void SELECTPICTURES()
   
{                                        
              String pid = numbre.getText();
              String Sear="SELECT * FROM PITRESS where STUDENTNUMDER= ?";
             try
                {
                    String url="jdbc:derby://localhost:1527/Tutorial";
                    String username = "Tutorial";
                    String password = "Tutorial";
                    Connection con= DriverManager.getConnection(url, username, password);
                    PreparedStatement ps= con.prepareStatement(Sear); 
                    ps.setString(1, pid);
                    ResultSet rs = ps.executeQuery();
              
             if ( rs.next() == true )
                {
                 
                 byte[]imag= rs.getBytes("PICT");
                 ImageIcon in= new ImageIcon(imag);
                 Image img = in.getImage();
                 Image newImg = img.getScaledInstance(180, 150, Image.SCALE_SMOOTH);
                 
                 ImageIcon image = new ImageIcon(newImg);
                 getimage.setIcon(image);
                }
             else
             {
                 System.out.println("Incore");
                 
             }
                }
                catch ( Exception e )
                {
                System.out.println(""+e.getMessage());
                }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Monday;
    private javax.swing.JCheckBox Saturday;
    private javax.swing.JCheckBox Sunday;
    public static javax.swing.JLabel TIMESTUDENT;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JButton apply;
    private javax.swing.JCheckBox availecture1;
    private javax.swing.JCheckBox availecture2;
    private javax.swing.JCheckBox availecture3;
    public javax.swing.JLabel couse;
    private javax.swing.JLabel getimage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lectunamessss1;
    private javax.swing.JLabel lecturess2;
    private javax.swing.JLabel money1;
    private javax.swing.JLabel money2;
    private javax.swing.JLabel money3;
    public javax.swing.JLabel numbre;
    public javax.swing.JLabel studentAva;
    public javax.swing.JLabel time;
    public javax.swing.JLabel timesss;
    // End of variables declaration//GEN-END:variables
}
